___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [1]:
import numpy as np # YOUR CODE IS HERE



### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [2]:
my_list = np.array([5, 10, 15, 20, 25]) # YOUR CODE IS HERE
my_list


array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros. 

In [3]:
arr1 = np.zeros((5, 5)) # YOUR CODE IS HERE
arr1


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [4]:
arr2 = np.array(([1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]))
np.array(arr2)  #YOUR CODE IS HERE
 


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [5]:
np.array(arr2).dtype

dtype('int64')

### 5. Make all the values of the array above with the value of 7.

In [6]:
arr3 = np.full((4,4), 7) # YOUR CODE IS HERE
np.array(arr3)



array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [7]:
np.full((4,4), arr3) # YOUR CODE IS HERE




array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive). 

In [8]:
arr4 = np.arange(2, 17, 2)   # YOUR CODE IS HERE
np.array(arr4)



array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [9]:
arr5 =[[0,  1,  2,  3,  4],  [5,  6,  7,  8,  9], [10, 11, 12, 13, 14], [15, 16,
       17, 18, 19], [20, 21, 22, 23, 24]] # YOUR CODE IS HERE
np.array(arr5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [26]:
np.arange(0, 25).reshape(5, 5)  # YOUR CODE IS HERE



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 10. Create randomly 5 numbers with numpy.

In [28]:
np.random.rand(5)# YOUR CODE IS HERE



array([0.50544513, 0.63527306, 0.20705167, 0.06473306, 0.4983228 ])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [29]:
arr6 = np.random.rand(25).reshape(5, 5)# YOUR CODE IS HERE
arr6


array([[0.15318046, 0.01110688, 0.38645751, 0.81064314, 0.48689922],
       [0.64756883, 0.8768069 , 0.6681032 , 0.32509462, 0.21204702],
       [0.26320866, 0.66287296, 0.02505762, 0.57846668, 0.21613191],
       [0.52345901, 0.34686395, 0.76470384, 0.73628352, 0.8757633 ],
       [0.10509396, 0.10459074, 0.02565811, 0.82845438, 0.96266033]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [31]:
arr7 = np.random.randint(20, size = (3, 4))# YOUR CODE IS HERE
arr7

array([[18,  0, 10,  4],
       [ 0,  1,  5, 18],
       [12, 10, 17, 10]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [38]:
ranarr = np.random.randint(0,50,48)
ranarr


array([17, 10,  4, 48, 44,  7, 37, 28,  1, 29, 28, 25, 12, 16, 36, 41, 37,
       49, 13, 33,  9, 36, 13, 20, 38, 41, 16, 25, 49, 43, 47, 26, 14, 29,
       30,  6, 21, 12,  5,  1, 37,  9, 32, 27, 34, 14, 37,  3])

In [39]:
ranarr.reshape(6, 8)

array([[17, 10,  4, 48, 44,  7, 37, 28],
       [ 1, 29, 28, 25, 12, 16, 36, 41],
       [37, 49, 13, 33,  9, 36, 13, 20],
       [38, 41, 16, 25, 49, 43, 47, 26],
       [14, 29, 30,  6, 21, 12,  5,  1],
       [37,  9, 32, 27, 34, 14, 37,  3]])

In [42]:
ranarr.reshape(4, 12)

array([[17, 10,  4, 48, 44,  7, 37, 28,  1, 29, 28, 25],
       [12, 16, 36, 41, 37, 49, 13, 33,  9, 36, 13, 20],
       [38, 41, 16, 25, 49, 43, 47, 26, 14, 29, 30,  6],
       [21, 12,  5,  1, 37,  9, 32, 27, 34, 14, 37,  3]])

In [41]:
ranarr1 = np.random.randint(0, 50, size = (6, 8))
ranarr1

array([[12, 28,  1, 42,  5, 25, 27,  1],
       [ 6, 45, 46, 48, 10, 29, 45, 43],
       [42,  1,  8, 19, 39, 45,  8, 28],
       [34, 35,  3, 49, 29, 13,  4, 14],
       [ 9, 41, 15,  0, 20, 10,  9, 25],
       [43, 33, 26, 45, 42, 47, 48,  3]])

In [43]:
ranarr.reshape(-1, 8) # YOUR CODE IS HERE (RESHAPING WITH -1)



array([[17, 10,  4, 48, 44,  7, 37, 28],
       [ 1, 29, 28, 25, 12, 16, 36, 41],
       [37, 49, 13, 33,  9, 36, 13, 20],
       [38, 41, 16, 25, 49, 43, 47, 26],
       [14, 29, 30,  6, 21, 12,  5,  1],
       [37,  9, 32, 27, 34, 14, 37,  3]])

In [44]:
ranarr.reshape(6, -1) # YOUR CODE IS HERE (RESHAPING WITH -1)


array([[17, 10,  4, 48, 44,  7, 37, 28],
       [ 1, 29, 28, 25, 12, 16, 36, 41],
       [37, 49, 13, 33,  9, 36, 13, 20],
       [38, 41, 16, 25, 49, 43, 47, 26],
       [14, 29, 30,  6, 21, 12,  5,  1],
       [37,  9, 32, 27, 34, 14, 37,  3]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [61]:
# YOUR CODE IS HERE 
mat = np.arange(1, 17).reshape(4, 4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [57]:
mat[1:3,1:3]# YOUR CODE IS HERE 


array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [63]:
mat[:,0]  # YOUR CODE IS HERE 


array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [68]:
mat[1, ::2] # YOUR CODE IS HERE 


array([5, 7])

### 17.Assign 77 to every cell in 3rd column.

In [72]:
mat[:,2:3] = 77 # YOUR CODE IS HERE 
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [76]:
a = mat[1, 0] # YOUR CODE IS HERE 
b = mat [3, 2]
np.array([a,b])

array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [77]:
mat[1::2, 0::2]# YOUR CODE IS HERE 


array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [78]:
mat # LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 



array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [79]:
mat[mat<10] # LET US FIND THE VALUES SMALLER THAN 10 IN "mat" 

# YOUR CODE IS HERE 



array([1, 2, 4, 5, 6, 8, 9])

In [80]:
mat[mat>12]# LET US FIND THE VALUES BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 



array([77, 77, 77, 13, 14, 77, 16])

In [82]:
a = mat[mat<10] + mat[mat>12] # LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat" 
a
# YOUR CODE IS HERE 



array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [83]:
a.std() # YOUR CODE IS HERE 



29.700546274093877

### 22. Get the sum of the 2nd column in the original "mat".

In [84]:
mat # LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 



array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [86]:
mat[:,2] = [3, 7, 11, 15]# LET OBTAIN THE ORIGINAL ARRAY OF "mat" 
mat
# YOUR CODE IS HERE 



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [89]:
mat[:,1].sum() # YOUR CODE IS HERE 



32

### 23. Get the median, mean and std of 3rd column in "mat".

In [90]:
mat # LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [99]:
mat[:,2] # LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE 

# YOUR CODE IS HERE 



array([ 3,  7, 11, 15])

In [100]:
mat[2:,:]# WHAT IF WE ARE INTERESTED IN THE 3RD ROW? 

# YOUR CODE IS HERE 



array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [106]:
print(np.median(mat[:,2]))

print(np.median(mat[2,:]))
# LET US GET MEDIAN VALUE 

# YOUR CODE IS HERE 



9.0
10.5


In [108]:
print(mat[:,2].mean()) # LET US GET MEAN VALUE 
print(mat[2,:].mean())
# YOUR CODE IS HERE 



9.0
10.5


In [109]:
print(mat[:,2].std())  # LET US GET STANDART DEVIATION (std) VALUE 
print(mat[2,:].std())
# YOUR CODE IS HERE 



4.47213595499958
1.118033988749895


## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [111]:
import pandas as pd

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [113]:
df = pd.read_csv("Salaries.csv")
df 
# LET US READ Salaries.csv 

# YOUR CODE IS HERE 



FileNotFoundError: ignored

In [ ]:
df = pd.# LET US LOOK AT THE FIRST 5 ROWS

# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [ ]:
# LET US GET A SAMPLE 

# YOUR CODE IS HERE 



Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [ ]:
# YOUR CODE IS HERE 



In [ ]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS  

# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [ ]:
# YOUR CODE IS HERE 



In [ ]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 



In [ ]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 



### Print out max and avg values in the column of "Totalpay".

In [ ]:
# LET US FIND THE MAXIMUM TOTALPAY

# YOUR CODE IS HERE 



In [ ]:
# LET US FIND THE AVERAGE TOTALPAY

# YOUR CODE IS HERE 



### How many records in the TotalPay column are there bigger than avg TotalPay?

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [ ]:
# YOUR CODE IS HERE 



### How much does ALBERT PARDINI make money (including benefits)?

In [ ]:
# YOUR CODE IS HERE 



### Who is the lowest paid person?

In [ ]:
# YOUR CODE IS HERE 



### What are the unique Jobs in dataset?

In [ ]:
# YOUR CODE IS HERE 



### List the top 3 least common Jobs in the dataset.

In [ ]:
# YOUR CODE IS HERE 



### How many people earned more than avg in 2012?

In [ ]:
# YOUR CODE IS HERE 



### How many people have a title of Manager in their jobs?

In [ ]:
# USE APPLY FUNCTION

# YOUR CODE IS HERE 



### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________